version: '3'
services:
  registry:
    image: registry:2
    container_name: docker-cache
    ports:
      - 5000:5000
    environment:
      REGISTRY_PROXY_REMOTEURL: https://registry-1.docker.io
    volumes:
      - ./registry-data:/var/lib/registry
    restart: always
