version: '3'
services:
  docker-cache:
    image: registry:2
    container_name: docker-cache
    ports:
      - "5000:5000"
    volumes:
      - ./registry-data:/var/lib/registry
    restart: unless-stopped